# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_id', models.IntegerField(default=0)),
                ('Comment_date', models.DateTimeField(verbose_name='date published')),
                ('Comment_author', models.CharField(max_length=20)),
                ('Comment_topic_belong_to', models.IntegerField(default=0)),
                ('Comment_content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_id', models.IntegerField(default=0)),
                ('Equipment_user_list', models.CharField(max_length=500)),
                ('Equipment_content', models.CharField(max_length=300)),
                ('Equipment_begin_date', models.DateTimeField(verbose_name='date begin')),
                ('Equipment_end_date', models.DateTimeField(verbose_name='date end')),
            ],
        ),
        migrations.CreateModel(
            name='Item_id_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_num', models.IntegerField(default=0)),
                ('Comment_num', models.IntegerField(default=0)),
                ('Topic_num', models.IntegerField(default=0)),
                ('Equipment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_id', models.IntegerField(default=0)),
                ('Topic_date', models.DateTimeField(verbose_name='date published')),
                ('Topic_content', models.CharField(max_length=500)),
                ('Topic_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_accont', models.CharField(max_length=20)),
                ('user_nick_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
