# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydy_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Topic_title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
